src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CandidateHelper.cls
public with sharing class CandidateHelper {
	
	public static void checkemail(List<Candidate__c> c)
	{
		set<string> emailid = new set<string>();
		
		for(candidate__c cc : [select Email__c from candidate__c])
		{
			if(cc.email__c !=null)
			{
				emailid.add(cc.email__c);
			}
		}
		
		for(candidate__c aa : c)
		{
			if(emailid.contains(aa.email__c))
			{
				aa.email__c.addError('Email Already Exists. Please enter different email id');
			}
		}
	}

}