src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/InsertCandidate.cls
global class InsertCandidate {
	
	webservice static string getcandidateinfo(string fname, string lname, string city)
	{
		candidate__c c = new candidate__c();
		list<candidate__c> mycan = new List<candidate__c>();
		c.First_Name__c=fname;
		c.Last_Name__c=lname;
		c.City__c=city;
		
		//mycan.add(c);
		
		insert c;
		
		if (c.Id == null)
		{
			return 'Error occured during candidate creation';
		}
		else
		{
			return 'Successfully inserted candidate' + c.Id;
		}
		
		
		/*List<database.saveresult> sr = database.insert(mycan,false);
		
		for(database.saveresult srs:sr)
		{
				if (srs.isSuccess())
				{
					return 'Successfully inserted candidate';
				}
				else
				{
					return 'Error occured during candidate creation';
				}
		}*/
	}

}