src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>variable_pay__c</fullName>
        <label>variable pay</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Salary__c.object
<CustomObject>
    <label>Salary</label>
    <nameField>
        <displayFormat>PAY-{0000}</displayFormat>
        <label>Salary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/EmployeeHelper_Test123.cls
@isTest
private class EmployeeHelper_Test123 {

    static testMethod void positivetest() 
    {
        employee__c e1 = new employee__c(name='E1', salary__c=10000);
        employee__c e2 = new employee__c(name='E2', salary__c=20000);
        employee__c e3 = new employee__c(name='E3', salary__c=30000);
        
        list<employee__c> elist = new list<employee__c>{e1,e2,e3};
        
        database.insert(elist,false);
        
        map<id,employee__c> m = new map<id,employee__c>(elist);
        
        List<employee__c> ee = [select variable_pay__c from employee__c where id =: m.keyset()];
        
 try{
    for(employee__c x : ee)
    {
    system.assertequals(x.variable_pay__c,x.salary__c*0.3); 
    }       
 }
 catch(system.exception e)
 {
    system.debug('something is wrong.....'+e.getmessage());
 }
}
}