src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Max_Pay__c</fullName>
        <label>Max Pay</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Pay__c</fullName>
        <label>Min Pay</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/positionBatch.cls
global class positionBatch implements database.batchable<sObject>, database.stateful {
	
	Integer rCount = 0;
	
	global database.querylocator start(database.batchablecontext bc)
	{
		database.querylocator qc = database.getQuerylocator('select name,min_pay__c, max_pay__c from position__c');
		
		return qc;
	}
	
	global void execute(database.batchablecontext bc, List<sObject> olist)
	{
		
		for(sObject s : olist)
		{
			position__c p = (position__c)s;
			
			if (p.min_pay__c == null)
			{
				p.min_pay__c = 1000;
				rCount = rCount+1;
			}
			if (p.max_pay__c == null)
			{
				p.max_pay__c = 5000;
			}
			upsert p;
			system.debug('Position ' + p.name + 'processed in batch class');
		}
		
	}
	
	global void finish(database.batchablecontext bc)
	{
		system.debug('No of records updated : ' + rCount);
	}

}