src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Max_Pay__c</fullName>
        <label>Max Pay</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Pay__c</fullName>
        <label>Min Pay</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/positionextension.cls
public class positionextension {

    private Apexpages.standardcontroller ctr;
    position__c p;
    public double hra {get; set;}
    public double ta {get; set;}
    public double gross {get; set;}
    
    public positionextension(ApexPages.StandardController controller) {
     this.ctr=controller;
     p=(position__c)ctr.getRecord();

    }

    public void mypage()
    {
        double avgpay = (p.max_pay__c-p.min_pay__c)/2;
        hra = avgpay*0.3;
        ta=avgpay*0.15;
        gross=avgpay+hra+ta;
        //return ctr.view().setRedirect(true);
    }

}