src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/demosettergetter.cls
public class demosettergetter {

public string banner {
get
{
    string empbanner = 'Apex Controllers';
    return empbanner;
}
}

public List<Position__c> plist{
get
{
List<position__c> pdata = [select name,department__c from position__c limit 10];
return pdata;
}

}
public string err {get; set;}
public string ename
{
get;
set 
{
    If(ename==null){err = 'Field is null. Please enter a value';}
}
}

public pageReference disp()
{
return null;
}

}